# Generated by Django 5.1.4 on 2024-12-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="registration_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["brand", "year"], name="cars_car_brand_56f3d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["date_created"], name="cars_car_date_cr_f83abc_idx"
            ),
        ),
    ]
